In [2]:
import numpy as np
import pandas as pd

In [3]:
#array supports element wise operations
arr1 = np.array(range(1000000))
arr1**2

array([         0,          1,          4, ..., -733379959, -731379964,
       -729379967])

In [4]:
#proving that numpy is faster
import time
st = time.time()
list1 = list(range(1000000))
list1 = [i**2 for i in list1]
et = time.time()
print(f"list operation time is {et-st}")

st = time.time()
arr1 = np.array(range(1000000))
arr1**2
et = time.time()
print(f"Array operation time is {et-st}")

list operation time is 12.598976850509644
Array operation time is 7.907897472381592


Read about vectorization which is parellel processing which helps array in performing faster code

In [5]:
#dimensions of an array
arr = np.array(range(10))
print(arr.ndim)
print(arr.shape)

1
(10,)


In [6]:
#multi dimensional array
arr2 = np.array([[1,2],[2,3],[3,4]])
print(arr2.ndim)
print(arr2.shape)

2
(3, 2)


Q: how to get total elemants in an array

#Array can have as many dimensions as we can as long as memory supports

In [7]:
# Method to create list directly
arr = np.arange(10)
arr.shape

(10,)

In [8]:
arr = np.arange(1,5,2)
arr

array([1, 3])

In [9]:
#stepsize in arange can have float step size which is not available in range function
arr = np.arange(1,5,0.5)
arr

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [10]:
#overwriting multiple elements
arr = np.arange(5)
arr[1:3] = 100
arr

array([  0, 100, 100,   3,   4])

In [11]:
arr = np.arange(10)
print(arr)
arr += 5    #adding 5 to each element in array
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [12]:
#checking datatype of array
arr = np.arange(5)
print(arr.dtype)
arr = np.array([1,2,3,4.0])
print(arr.dtype)

int32
float64


In [13]:
#we can hardcode datatype while creating an array while using np.array function
arr = np.array([1,2,3,4], dtype = 'float')
print(arr.dtype)
arr = np.array([1,2,3,4.5], dtype = 'int')
print(arr.dtype)
print(arr)


float64
int32
[1 2 3 4]


In [14]:
#convert existing array to different datatype
arr = np.array(['1','2'])
print(arr.dtype)
arr = arr.astype('int')
print(arr.dtype)

<U1
int32


Indexing

In [21]:
m = np.arange(12)
print(m)
print(m[0])
print(m[-1])
print(m[[2,3,6]]) #accessing multiple elements with indexing
print(m[[2,3,6,3]])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
0
11
[2 3 6]
[2 3 6 3]
