<a href="https://colab.research.google.com/github/Grey-hatcoder/My-Coding-files/blob/main/numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [17]:
arr = np.arange(16)

In [18]:
arr.reshape(8,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
print(arr.reshape(8,-1))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [21]:
arr = arr.reshape(8,-1).T

In [22]:
arr

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 1,  3,  5,  7,  9, 11, 13, 15]])

In [10]:
arr[0,[0,1,2]]

array([0, 2, 4])

In [39]:
mat = np.arange(12).reshape(3,-1)

In [40]:
mat


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
mat.shape

(3, 4)

In [32]:
np.mean(mat,axis=0) #calculating columnwise mean, rows are changing, hence axis =0

array([4., 5., 6., 7.])

In [33]:
np.mean(mat,axis=1) #calculating rowwise mean, column are changing, hence axis =1

array([1.5, 5.5, 9.5])

In [34]:
mat = mat.reshape(2,2,3)

In [35]:
mat


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [38]:
np.mean(mat, axis =0)

array([[3., 4., 5.],
       [6., 7., 8.]])

In [48]:
price = np.array([45,55,60,75,40,90])
price = price * 0.9

UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [50]:
np.unique(price)

array([40, 45, 55, 60, 75, 90])